# Dockerfile to build image for
# Database 
FROM openstack_base:latest
LABEL maintainer="Yusuke Hayashi <yusuke.hayashi.710@gmail.com>"

# Install packages
RUN DEBIAN_FRONTEND=noninteractive apt install -y mariadb-server python-pymysql

# ARG & ENV
ARG CTRL_IP

# Setup
RUN echo "export PS1=\"\u@db:\w\$ \"" >> ~/.bashrc
COPY scripts/start_db.sh ./
COPY scripts/restart_db.sh ./
COPY conf/db/99-openstack.cnf /etc/mysql/mariadb.conf.d/99-openstack.cnf
RUN sed -i "s/CTRL_IP/${CTRL_IP}/g" /etc/mysql/mariadb.conf.d/99-openstack.cnf

# Copy additional scripts for operation.
COPY utils/add_db_user.sh ./

# Launch service
CMD ["./start_db.sh"]
