# Dockerfile to build image for
# Message Queue
FROM openstack_base:latest
LABEL maintainer="Yusuke Hayashi <yusuke.hayashi.710@gmail.com>"

# Install packages
RUN DEBIAN_FRONTEND=noninteractive apt install -y rabbitmq-server

# Setup
RUN echo "export PS1=\"\u@mq:\w\$ \"" >> ~/.bashrc
COPY scripts/start_mq.sh ./
COPY scripts/restart_mq.sh ./
COPY scripts/setup_mq.sh ./

COPY conf/mq/rabbitmq-env.conf /etc/rabbitmq/rabbitmq-env.conf

# Launch service
CMD ["./start_mq.sh"]
